export enum MessageType {
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_GET_BY_ID = 'ORDER_GET_BY_ID',
  ORDER_GET_LIST = 'ORDER_GET_LIST',
  ORDER_CHECK_STATUS = 'ORDER_CHECK_STATUS',
  PAYMENT_HANDLE = 'PAYMENT_HANDLE',
}
